/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.budgieui;

import budgieapp.TransportationCost;
import java.awt.Color;
import java.awt.TextField;

//import my.budgieui.*;
/**
 *
 * @author Jon
 */
public class FinancialInfoUI extends javax.swing.JFrame {
    
    /**
     * Creates new form FinancialInfoUI
     */
    public String textBills;
    public String textIncome;
    public String textLivingExpense;
    public String textOtherExpense;
            
    public String submitTest;
    public boolean submitBool = false;
    
    public static FinancialInfoUI financialInfoUI;
    public FinancialInfoUI() {
        
        getContentPane().setBackground(Color.white);
        financialInfoUI = this;
        initComponents();
        budgieTitle1.setEditable(false);
        budgieTitle2.setEditable(false);
        textFieldEnterBills.setEditable(false);
        textFieldEnterIncome.setEditable(false);
        textFieldEnterLivingExpense.setEditable(false);
        textFieldEnterOtherExpense.setEditable(false);
        budgieTitle1.setBackground(Color.white);
        budgieTitle2.setBackground(Color.white);
        textFieldEnterBills.setBackground(Color.white);
        textFieldEnterIncome.setBackground(Color.white);
        textFieldEnterLivingExpense.setBackground(Color.white);
        textFieldEnterOtherExpense.setBackground(Color.white);
        userMonthlyBills.setText("0");
        userMonthlyLivingExpense.setText("0");
        userMonthlyIncome.setText("0");
        userMonthlyOtherExpense.setText("0");
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        textFieldEnterIncome = new javax.swing.JTextField();
        userMonthlyIncome = new java.awt.TextField();
        submitButton = new javax.swing.JButton();
        budgieTitle1 = new javax.swing.JTextField();
        textFieldEnterLivingExpense = new javax.swing.JTextField();
        textFieldEnterOtherExpense = new javax.swing.JTextField();
        textFieldEnterBills = new javax.swing.JTextField();
        budgieTitle2 = new javax.swing.JTextField();
        userMonthlyLivingExpense = new java.awt.TextField();
        userMonthlyBills = new java.awt.TextField();
        userMonthlyOtherExpense = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        notificationLabel = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EnterFinancialInfoPage");
        setBackground(new java.awt.Color(0, 255, 255));

        textFieldEnterIncome.setBackground(new java.awt.Color(240, 240, 240));
        textFieldEnterIncome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldEnterIncome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldEnterIncome.setText("Enter Monthly Income: ");
        textFieldEnterIncome.setBorder(null);
        textFieldEnterIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEnterIncomeActionPerformed(evt);
            }
        });

        userMonthlyIncome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userMonthlyIncome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userMonthlyIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMonthlyIncomeActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(51, 204, 255));
        submitButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        submitButton.setText("Submit Information");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        budgieTitle1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        budgieTitle1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        budgieTitle1.setText("Budgie");
        budgieTitle1.setBorder(null);
        budgieTitle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgieTitle1ActionPerformed(evt);
            }
        });

        textFieldEnterLivingExpense.setBackground(new java.awt.Color(240, 240, 240));
        textFieldEnterLivingExpense.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldEnterLivingExpense.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldEnterLivingExpense.setText("Enter Monthly Living Expense: ");
        textFieldEnterLivingExpense.setBorder(null);
        textFieldEnterLivingExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEnterLivingExpenseActionPerformed(evt);
            }
        });

        textFieldEnterOtherExpense.setBackground(new java.awt.Color(240, 240, 240));
        textFieldEnterOtherExpense.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldEnterOtherExpense.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldEnterOtherExpense.setText("Enter Any Other Monthly Expense:");
        textFieldEnterOtherExpense.setBorder(null);
        textFieldEnterOtherExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEnterOtherExpenseActionPerformed(evt);
            }
        });

        textFieldEnterBills.setBackground(new java.awt.Color(240, 240, 240));
        textFieldEnterBills.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldEnterBills.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldEnterBills.setText("Enter Monthly Bills Expense: ");
        textFieldEnterBills.setBorder(null);
        textFieldEnterBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEnterBillsActionPerformed(evt);
            }
        });

        budgieTitle2.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        budgieTitle2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        budgieTitle2.setText("Finance Made Simple");
        budgieTitle2.setBorder(null);
        budgieTitle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgieTitle2ActionPerformed(evt);
            }
        });

        userMonthlyLivingExpense.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userMonthlyLivingExpense.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userMonthlyLivingExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMonthlyLivingExpenseActionPerformed(evt);
            }
        });

        userMonthlyBills.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userMonthlyBills.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userMonthlyBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMonthlyBillsActionPerformed(evt);
            }
        });

        userMonthlyOtherExpense.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userMonthlyOtherExpense.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userMonthlyOtherExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMonthlyOtherExpenseActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budgieapp/pictures/budgie bird.jpg"))); // NOI18N

        notificationLabel.setBackground(new java.awt.Color(255, 255, 255));
        notificationLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        notificationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notificationLabel.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(budgieTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(budgieTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textFieldEnterBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEnterOtherExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEnterLivingExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEnterIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userMonthlyIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userMonthlyLivingExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userMonthlyOtherExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userMonthlyBills, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addGap(263, 263, 263))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(notificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(budgieTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(budgieTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userMonthlyIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEnterIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldEnterLivingExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userMonthlyLivingExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userMonthlyBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEnterBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userMonthlyOtherExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEnterOtherExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addComponent(notificationLabel)
                .addGap(18, 18, 18)
                .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldEnterIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEnterIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEnterIncomeActionPerformed

    private void budgieTitle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgieTitle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgieTitle1ActionPerformed

    private void textFieldEnterLivingExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEnterLivingExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEnterLivingExpenseActionPerformed

    private void textFieldEnterOtherExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEnterOtherExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEnterOtherExpenseActionPerformed

    private void textFieldEnterBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEnterBillsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEnterBillsActionPerformed

    private void budgieTitle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgieTitle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgieTitle2ActionPerformed

    private void userMonthlyIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMonthlyIncomeActionPerformed
        // TODO add your handling code here:
        //String income = userMonthlyIncome.getText();
        //System.out.println(income);
        
    }//GEN-LAST:event_userMonthlyIncomeActionPerformed

    private void userMonthlyLivingExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMonthlyLivingExpenseActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userMonthlyLivingExpenseActionPerformed

    private void userMonthlyBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMonthlyBillsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userMonthlyBillsActionPerformed

    private void userMonthlyOtherExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMonthlyOtherExpenseActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userMonthlyOtherExpenseActionPerformed

    public String getSubmitTest() {
        return submitTest;
    }

    public void setSubmitTest(String submitTest) {
        this.submitTest = submitTest;
    }

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        textBills = userMonthlyBills.getText();
        textLivingExpense = userMonthlyLivingExpense.getText();
        textIncome = userMonthlyIncome.getText();
        textOtherExpense = userMonthlyOtherExpense.getText();
        submitBool = true;
        
        //System.out.println(submitTest);
    }//GEN-LAST:event_submitButtonActionPerformed
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinancialInfoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinancialInfoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinancialInfoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinancialInfoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new FinancialInfoUI().setVisible(true);
                
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField budgieTitle1;
    private javax.swing.JTextField budgieTitle2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel notificationLabel;
    public javax.swing.JButton submitButton;
    private javax.swing.JTextField textFieldEnterBills;
    private javax.swing.JTextField textFieldEnterIncome;
    private javax.swing.JTextField textFieldEnterLivingExpense;
    private javax.swing.JTextField textFieldEnterOtherExpense;
    public java.awt.TextField userMonthlyBills;
    public java.awt.TextField userMonthlyIncome;
    public java.awt.TextField userMonthlyLivingExpense;
    public java.awt.TextField userMonthlyOtherExpense;
    // End of variables declaration//GEN-END:variables
}
