/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.budgieui;

import java.awt.Color;

/**
 *
 * @author jonpi
 */
public class LoanCalcUI extends javax.swing.JFrame {

    /**
     * Creates new form LoanCalcUI
     */
    public LoanCalcUI() {
        
        initComponents();
        getContentPane().setBackground(Color.white);
        budgieTitle1.setEditable(false);
        budgieTitle2.setEditable(false);
        budgieTitle1.setBackground(Color.white);
        budgieTitle2.setBackground(Color.white);
        textFieldEnterInterest.setBackground(Color.white);
        textFieldEnterLoanAmount.setBackground(Color.white);
        textFieldLoanType.setBackground(Color.white);
        textFieldLoanDuration.setBackground(Color.white);
        textFieldLoanWithInterest.setBackground(Color.white);
        textFieldMonthly.setBackground(Color.white);
        textFieldTotalLoanWithInterest.setBackground(Color.white);
        textFieldMonthlyPayment.setBackground(Color.white);
        textFieldTotalLoanWithInterest.setEditable(false);
        textFieldMonthlyPayment.setEditable(false);
        textFieldLoanWithInterest.setEditable(false);
        textFieldMonthly.setEditable(false);
        textFieldLoanDuration.setEditable(false);
        textFieldLoanType.setEditable(false);
        textFieldEnterLoanAmount.setEditable(false);
        textFieldEnterInterest.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        budgieTitle1 = new javax.swing.JTextField();
        budgieTitle2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldEnterLoanAmount = new javax.swing.JTextField();
        textFieldEnterInterest = new javax.swing.JTextField();
        userInterestRate = new java.awt.TextField();
        userLoanAmount = new java.awt.TextField();
        textFieldLoanDuration = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        textFieldLoanType = new javax.swing.JTextField();
        javax.swing.JComboBox<String> jComboBox2 = new javax.swing.JComboBox<>();
        javax.swing.JButton submitInfoButton = new javax.swing.JButton();
        textFieldLoanWithInterest = new javax.swing.JTextField();
        textFieldMonthly = new javax.swing.JTextField();
        textFieldTotalLoanWithInterest = new javax.swing.JTextField();
        textFieldMonthlyPayment = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        budgieTitle1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        budgieTitle1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        budgieTitle1.setText("Budgie");
        budgieTitle1.setBorder(null);
        budgieTitle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgieTitle1ActionPerformed(evt);
            }
        });

        budgieTitle2.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        budgieTitle2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        budgieTitle2.setText("Finance Made Simple");
        budgieTitle2.setBorder(null);
        budgieTitle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgieTitle2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budgieapp/pictures/budgie bird.jpg"))); // NOI18N

        textFieldEnterLoanAmount.setBackground(new java.awt.Color(240, 240, 240));
        textFieldEnterLoanAmount.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldEnterLoanAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldEnterLoanAmount.setText("Enter Loan Amount:");
        textFieldEnterLoanAmount.setBorder(null);
        textFieldEnterLoanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEnterLoanAmountActionPerformed(evt);
            }
        });

        textFieldEnterInterest.setBackground(new java.awt.Color(240, 240, 240));
        textFieldEnterInterest.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldEnterInterest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldEnterInterest.setText("Enter Interest Rate:");
        textFieldEnterInterest.setBorder(null);
        textFieldEnterInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEnterInterestActionPerformed(evt);
            }
        });

        userInterestRate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userInterestRate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userInterestRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInterestRateActionPerformed(evt);
            }
        });

        userLoanAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userLoanAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userLoanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoanAmountActionPerformed(evt);
            }
        });

        textFieldLoanDuration.setBackground(new java.awt.Color(240, 240, 240));
        textFieldLoanDuration.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldLoanDuration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldLoanDuration.setText("Loan Duration:");
        textFieldLoanDuration.setBorder(null);
        textFieldLoanDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLoanDurationActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        textFieldLoanType.setBackground(new java.awt.Color(240, 240, 240));
        textFieldLoanType.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldLoanType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldLoanType.setText("Select Loan Type:");
        textFieldLoanType.setBorder(null);
        textFieldLoanType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLoanTypeActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home", "Auto" }));

        submitInfoButton.setBackground(new java.awt.Color(153, 255, 255));
        submitInfoButton.setText("Submit Information");
        submitInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitInfoButtonActionPerformed(evt);
            }
        });

        textFieldLoanWithInterest.setBackground(new java.awt.Color(240, 240, 240));
        textFieldLoanWithInterest.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldLoanWithInterest.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldLoanWithInterest.setText("Total Loan With Interest:");
        textFieldLoanWithInterest.setBorder(null);
        textFieldLoanWithInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLoanWithInterestActionPerformed(evt);
            }
        });

        textFieldMonthly.setBackground(new java.awt.Color(240, 240, 240));
        textFieldMonthly.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldMonthly.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldMonthly.setText("Monthly Payment:");
        textFieldMonthly.setBorder(null);
        textFieldMonthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMonthlyActionPerformed(evt);
            }
        });

        textFieldTotalLoanWithInterest.setBackground(new java.awt.Color(240, 240, 240));
        textFieldTotalLoanWithInterest.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldTotalLoanWithInterest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldTotalLoanWithInterest.setText("---");
        textFieldTotalLoanWithInterest.setBorder(null);
        textFieldTotalLoanWithInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTotalLoanWithInterestActionPerformed(evt);
            }
        });

        textFieldMonthlyPayment.setBackground(new java.awt.Color(240, 240, 240));
        textFieldMonthlyPayment.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldMonthlyPayment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldMonthlyPayment.setText("---");
        textFieldMonthlyPayment.setBorder(null);
        textFieldMonthlyPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMonthlyPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(budgieTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(budgieTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldEnterLoanAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEnterInterest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldLoanType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldLoanDuration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldMonthly, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldLoanWithInterest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(submitInfoButton))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(userLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox2, 0, 122, Short.MAX_VALUE)
                                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(userInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel2))
                                    .addComponent(textFieldMonthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldTotalLoanWithInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(budgieTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(budgieTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldLoanType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldLoanDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEnterLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEnterInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldLoanWithInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTotalLoanWithInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldMonthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void budgieTitle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgieTitle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgieTitle1ActionPerformed

    private void budgieTitle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgieTitle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgieTitle2ActionPerformed

    private void textFieldEnterLoanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEnterLoanAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEnterLoanAmountActionPerformed

    private void textFieldEnterInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEnterInterestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEnterInterestActionPerformed

    private void userInterestRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInterestRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInterestRateActionPerformed

    private void userLoanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoanAmountActionPerformed
        // TODO add your handling code here:
        //String income = userMonthlyIncome.getText();
        //System.out.println(income);
    }//GEN-LAST:event_userLoanAmountActionPerformed

    private void textFieldLoanDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLoanDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLoanDurationActionPerformed

    private void textFieldLoanTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLoanTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLoanTypeActionPerformed

    private void submitInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitInfoButtonActionPerformed
        // TODO add your handling code here:
        loanCalculations();
    }//GEN-LAST:event_submitInfoButtonActionPerformed

    private void textFieldLoanWithInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLoanWithInterestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLoanWithInterestActionPerformed

    private void textFieldMonthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMonthlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMonthlyActionPerformed

    private void textFieldTotalLoanWithInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTotalLoanWithInterestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTotalLoanWithInterestActionPerformed

    private void textFieldMonthlyPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMonthlyPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMonthlyPaymentActionPerformed
    private void loanCalculations(){
        int duration = 0;
        String loanAmountStr;
        String interestRateStr;
        float loanAmount;
        float interestRate;
        float totalInterest;
        float totalLoan;
        float monthlyCost;
        
        duration = (jComboBox1.getSelectedIndex() + 1) * 12;
        System.out.println(duration);
        loanAmountStr = userLoanAmount.getText();
        interestRateStr = userInterestRate.getText();
        loanAmount = Float.valueOf(loanAmountStr);
        interestRate = Float.valueOf(interestRateStr);
        
        totalInterest = loanAmount * interestRate;
        totalLoan = loanAmount + totalInterest;
        monthlyCost = totalLoan/duration;
        
        textFieldTotalLoanWithInterest.setText("$" + totalLoan);
        textFieldMonthlyPayment.setText("$" + monthlyCost);
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanCalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanCalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanCalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanCalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanCalcUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField budgieTitle1;
    private javax.swing.JTextField budgieTitle2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textFieldEnterInterest;
    private javax.swing.JTextField textFieldEnterLoanAmount;
    private javax.swing.JTextField textFieldLoanDuration;
    private javax.swing.JTextField textFieldLoanType;
    private javax.swing.JTextField textFieldLoanWithInterest;
    private javax.swing.JTextField textFieldMonthly;
    private javax.swing.JTextField textFieldMonthlyPayment;
    private javax.swing.JTextField textFieldTotalLoanWithInterest;
    public java.awt.TextField userInterestRate;
    public java.awt.TextField userLoanAmount;
    // End of variables declaration//GEN-END:variables
}
