/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.budgieui;

import java.awt.Color;

/**
 *
 * @author jonpi
 */
public class savingsUI extends javax.swing.JFrame {

    public boolean backFlag = false;

    /** Creates new form savingsUI */
    public savingsUI() {
        
        initComponents();
        getContentPane().setBackground(Color.white);
        budgieTitle1.setEditable(false);
        budgieTitle2.setEditable(false);
        budgieTitle1.setBackground(Color.white);
        budgieTitle2.setBackground(Color.white);
        
        resultLabel.setBackground(Color.white);
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        budgieTitle1 = new javax.swing.JTextField();
        budgieTitle2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        textFieldAmount = new javax.swing.JTextField();
        textFieldDuration = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();
        resultOutputLabel = new javax.swing.JLabel();
        notificationLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        budgieTitle1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        budgieTitle1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        budgieTitle1.setText("Budgie");
        budgieTitle1.setBorder(null);
        budgieTitle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgieTitle1ActionPerformed(evt);
            }
        });

        budgieTitle2.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        budgieTitle2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        budgieTitle2.setText("Finance Made Simple");
        budgieTitle2.setBorder(null);
        budgieTitle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgieTitle2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budgieapp/pictures/budgie bird.jpg"))); // NOI18N

        amountLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        amountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        amountLabel.setText("Enter amount needed to save:");

        durationLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        durationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        durationLabel.setText("Enter duration needed by (in months):");

        textFieldAmount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldAmount.setText("0");

        textFieldDuration.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldDuration.setText("0");

        resultLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultLabel.setText("You need to save this amount per month:");

        resultOutputLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        resultOutputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultOutputLabel.setText("---");

        notificationLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        notificationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notificationLabel.setText("---");

        submitButton.setBackground(new java.awt.Color(51, 204, 255));
        submitButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        submitButton.setText("Submit Information");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(budgieTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(budgieTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(amountLabel)
                                    .addComponent(durationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultOutputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(notificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(budgieTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(budgieTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountLabel)
                            .addComponent(textFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(durationLabel)
                            .addComponent(textFieldDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resultLabel)
                            .addComponent(resultOutputLabel))))
                .addGap(37, 37, 37)
                .addComponent(notificationLabel)
                .addGap(29, 29, 29)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void budgieTitle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgieTitle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgieTitle1ActionPerformed

    private void budgieTitle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgieTitle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgieTitle2ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        savingsCalculations();
    }//GEN-LAST:event_submitButtonActionPerformed
    private void savingsCalculations(){
        float userSavingsAmount;
        float userMonthsNeeded;
        float amountEachMonth;
        String amountStr;
        String durationStr;
        boolean errorFlag = false;
        resultOutputLabel.setText("");
        
        amountStr = textFieldAmount.getText();
        durationStr = textFieldDuration.getText();
        
        try{
        userSavingsAmount = Float.valueOf(amountStr);
        userMonthsNeeded = Float.valueOf(durationStr);
        if(userSavingsAmount > 10000000 || userMonthsNeeded > 10000000){
            notificationLabel.setText("Value Entered is To High. Please Enter New Value");
        }
        else if(userSavingsAmount < 0 || userMonthsNeeded < 0){
            notificationLabel.setText("Negative value entered. Please enter a positive value.");
        }
        else if(userSavingsAmount == 0 || userMonthsNeeded == 0){
            notificationLabel.setText("Please Enter a Value other than 0");
        }
        else if(userSavingsAmount > 0 || userMonthsNeeded > 0){
            errorFlag = true;
        }
        }
        catch(Exception e){
            notificationLabel.setText("Please enter a numerical value");
        }
        
        if (errorFlag == true){
            userSavingsAmount = Float.valueOf(amountStr);
            userMonthsNeeded = Float.valueOf(durationStr);
            amountEachMonth = userSavingsAmount / userMonthsNeeded;
            resultOutputLabel.setText("$ " + amountEachMonth);
        }
        
        
        
    }
    public void setFlag(boolean flag){
        flag = true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(savingsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(savingsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(savingsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(savingsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new savingsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField budgieTitle1;
    private javax.swing.JTextField budgieTitle2;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel resultOutputLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField textFieldAmount;
    private javax.swing.JTextField textFieldDuration;
    // End of variables declaration//GEN-END:variables

}
