/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budgieapp;

import java.awt.Color;
import java.awt.event.KeyEvent;
//import my.budgieui.Saver;

/**
 *
 * @author hacker lab
 */
public class TransportationCost extends javax.swing.JFrame {

    /**
     * Creates new form TransportationCost
     */
    public TransportationCost() {
        initComponents();
        getContentPane().setBackground(Color.white);
        rentRadioButton.setBackground(Color.white);
        ownRadioButton.setBackground(Color.white);
        budgieTitle1.setBackground(Color.white);
        budgieTitle1.setEditable(false);
        jLabel1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        distanceRadioGroup = new javax.swing.ButtonGroup();
        carTypeRadioGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        milePerGallonTextfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        costPerGallonTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        distanceTravelledTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        travelledCostTextField = new javax.swing.JTextField();
        rentRadioButton = new javax.swing.JRadioButton();
        ownRadioButton = new javax.swing.JRadioButton();
        carRentCostLebel = new javax.swing.JLabel();
        carRentCostTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        budgieTitle1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Finance Made Simple");

        milePerGallonTextfield.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        milePerGallonTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milePerGallonTextfieldActionPerformed(evt);
            }
        });
        milePerGallonTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                milePerGallonTextfieldKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Car type: ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Car's Gas Mileage (MPG)");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Gas Cost ($ / Gallon)");

        costPerGallonTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costPerGallonTextFieldActionPerformed(evt);
            }
        });
        costPerGallonTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costPerGallonTextFieldKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Distance Traveled (Miles / Day)");

        distanceTravelledTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanceTravelledTextFieldActionPerformed(evt);
            }
        });
        distanceTravelledTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                distanceTravelledTextFieldKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Travel Cost");

        travelledCostTextField.setEditable(false);
        travelledCostTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelledCostTextFieldActionPerformed(evt);
            }
        });

        carTypeRadioGroup.add(rentRadioButton);
        rentRadioButton.setSelected(true);
        rentRadioButton.setText("Rent");
        rentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentRadioButtonActionPerformed(evt);
            }
        });

        carTypeRadioGroup.add(ownRadioButton);
        ownRadioButton.setText("Own");
        ownRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownRadioButtonActionPerformed(evt);
            }
        });

        carRentCostLebel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        carRentCostLebel.setText("Car Payment / Month");

        carRentCostTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRentCostTextFieldActionPerformed(evt);
            }
        });
        carRentCostTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                carRentCostTextFieldKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Daily");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Weekly");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 204, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Monthly");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        budgieTitle1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        budgieTitle1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        budgieTitle1.setText("Budgie");
        budgieTitle1.setBorder(null);
        budgieTitle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgieTitle1ActionPerformed(evt);
            }
        });

        jLabel11.setText("$");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budgieapp/pictures/budgie bird.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(carRentCostLebel)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rentRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ownRadioButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(carRentCostTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(milePerGallonTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(costPerGallonTextField)
                                .addComponent(distanceTravelledTextField)
                                .addComponent(travelledCostTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(budgieTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(246, 246, 246))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(budgieTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ownRadioButton)
                            .addComponent(rentRadioButton)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carRentCostLebel)
                            .addComponent(carRentCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(milePerGallonTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(costPerGallonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(distanceTravelledTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(travelledCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void milePerGallonTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milePerGallonTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milePerGallonTextfieldActionPerformed

    private void costPerGallonTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costPerGallonTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costPerGallonTextFieldActionPerformed

    private void travelledCostTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelledCostTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_travelledCostTextFieldActionPerformed

    private void rentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentRadioButtonActionPerformed
        // TODO add your handling code here:
        carRentCostLebel.setVisible(true);
        carRentCostTextField.setVisible(true);
    }//GEN-LAST:event_rentRadioButtonActionPerformed

    private void carRentCostTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRentCostTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carRentCostTextFieldActionPerformed

    private void distanceTravelledTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanceTravelledTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distanceTravelledTextFieldActionPerformed

    private void ownRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownRadioButtonActionPerformed
        // TODO add your handling code here
        carRentCostLebel.setVisible(false);
        carRentCostTextField.setVisible(false);
    }//GEN-LAST:event_ownRadioButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       /* float carRentCost = 0;
        float milePerGallon = Float.valueOf(milePerGallonTextfield.getText());       
        float costPerGallon = Float.valueOf(costPerGallonTextField.getText());
        float distanceTravelled = Float.valueOf(distanceTravelledTextField.getText());
        System.out.println("milePerGallon: " + milePerGallon);
        System.out.println("costPerGallon: " + costPerGallon);
        System.out.println("distanceTravelled: " + distanceTravelled);
        
        
        if(rentRadioButton.isSelected())
            carRentCost = Integer.parseInt(carRentCostTextField.getText());
        
        System.out.println("carRentCost: " + carRentCost);
        float costPerMile = costPerGallon / milePerGallon;
        System.out.println("costPerMile: " + costPerMile);
                
        float travelledCost = costPerMile * distanceTravelled;
        System.out.println("travelledCost: " + travelledCost);
        travelledCostTextField.setText(String.valueOf(travelledCost + carRentCost)); */   
       
       calculateData(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        calculateData(7);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        calculateData(30);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void budgieTitle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgieTitle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgieTitle1ActionPerformed

    private void carRentCostTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carRentCostTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_carRentCostTextFieldKeyTyped

    private void milePerGallonTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_milePerGallonTextfieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_milePerGallonTextfieldKeyTyped

    private void costPerGallonTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costPerGallonTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_costPerGallonTextFieldKeyTyped

    private void distanceTravelledTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_distanceTravelledTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_distanceTravelledTextFieldKeyTyped

    private void calculateData(int calculationDuration)
    {
        float carRentCost = 0;
        float milePerGallon = Float.valueOf(milePerGallonTextfield.getText());       
        float costPerGallon = Float.valueOf(costPerGallonTextField.getText());
        float distanceTravelled = Float.valueOf(distanceTravelledTextField.getText());
        System.out.println("milePerGallon: " + milePerGallon);
        System.out.println("costPerGallon: " + costPerGallon);
        System.out.println("distanceTravelled: " + distanceTravelled);
        
        
        if(rentRadioButton.isSelected())
            carRentCost = Integer.parseInt(carRentCostTextField.getText());
        
        if(calculationDuration == 1)
        {        
            carRentCost = carRentCost / 30;
        }
        else if(calculationDuration == 7)
        {
            float perDayCarRent = carRentCost / 30;
            carRentCost = perDayCarRent * 7;
        }
        
        System.out.println("carRentCost: " + carRentCost);
        float costPerMile = costPerGallon / milePerGallon;
        System.out.println("costPerMile: " + costPerMile);
                
        float travelledCost = costPerMile * distanceTravelled * calculationDuration;
        System.out.println("travelledCost: " + travelledCost);
        travelledCostTextField.setText(String.valueOf(travelledCost + carRentCost)); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransportationCost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransportationCost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransportationCost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransportationCost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransportationCost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField budgieTitle1;
    private javax.swing.JLabel carRentCostLebel;
    private javax.swing.JTextField carRentCostTextField;
    private javax.swing.ButtonGroup carTypeRadioGroup;
    private javax.swing.JTextField costPerGallonTextField;
    private javax.swing.ButtonGroup distanceRadioGroup;
    private javax.swing.JTextField distanceTravelledTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField milePerGallonTextfield;
    private javax.swing.JRadioButton ownRadioButton;
    private javax.swing.JRadioButton rentRadioButton;
    private javax.swing.JTextField travelledCostTextField;
    // End of variables declaration//GEN-END:variables
}
